// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ruhmttcybwfnlkwkxgso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1aG10dGN5Yndmbmxrd2t4Z3NvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NzA4NTYsImV4cCI6MjA2OTM0Njg1Nn0.QT4vI4Vv8qzlMI49hnoJvB4WfwECVHOpw5D3UqZx4aI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});